# Railway Configuration for ONLSuggest
# Defines all services: Backend API, Frontend, PostgreSQL, Redis

[build]
builder = "nixpacks"
buildCommand = "echo 'Building services...'"

# Backend API Service
[[services]]
name = "onlsuggest-api"
source = "project1/backend"
dockerfile = "project1/backend/Dockerfile"

[services.healthcheck]
path = "/health"
interval = 30
timeout = 10

[services.env]
ENVIRONMENT = "production"
DEBUG = "false"

# Frontend Service
[[services]]
name = "onlsuggest-frontend"
source = "project1/frontend"

[services.build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[services.staticAssets]
outputPath = "dist"

# PostgreSQL Database
[[services]]
name = "postgres"
image = "postgres:15-alpine"

[services.env]
POSTGRES_DB = "onlsuggest"
POSTGRES_USER = "onlsuggest"

# Redis Cache
[[services]]
name = "redis"
image = "redis:7-alpine"
