# Render Blueprint for ONLSuggest
# Deploy entire stack: Backend + Frontend + PostgreSQL + Redis

services:
  # Backend API (FastAPI)
  - type: web
    name: onlsuggest-api
    runtime: docker
    dockerfilePath: ./project1/backend/Dockerfile
    dockerContext: ./project1/backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: onlsuggest-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: onlsuggest-redis
          type: redis
          property: connectionString
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://onlsuggest.onrender.com"]'
    healthCheckPath: /health

  # Frontend (React + Vite)
  - type: web
    name: onlsuggest-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        fromService:
          name: onlsuggest-api
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # PostgreSQL Database
  - name: onlsuggest-db
    plan: free
    databaseName: onlsuggest
    user: onlsuggest

  # Redis Cache
  - name: onlsuggest-redis
    plan: free
